name: build

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: msbuild "taskbar.sln" /p:Configuration=Release

    - name: List files in Release directory
      run: ls "bin/Release"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: taskbar-release
        path: "bin/Release/taskbar.exe"
